---
version: "3.9"

services:
  # --- System Model --- #
  structurizr:
    container_name: system-architecture-exams
    image: "structurizr/lite:latest"
    ports:
      - "8080:8080"
    volumes:
      - "./model:/usr/local/structurizr:rw"